name: Deploy Database
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: git checkout
    - uses: azure/sql-action@v2
      name: deploy sql files
      with:        
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './db-deploy/Database.sqlproj'
        action: 'publish'